### ISSUE TITLE
Segfault on createLogger

### ISSUE THREAD

**Issue by Jiropole** [trentm/node-bunyan#364]
I'm by no means a node expert, so this could be user error. However, my node app is crashing with a seg fault even with the basic `bunyan.createLogger({name: 'myapp'})` . Specifically node dies with *Process finished with exit code 139*. I couldn't find anything on this issue, so wanted to see if it rings any bells. The module was installed with `npm install bunyan`.

**Comment by Khez** [comment]
An exit code of 139 is the normal one for a segfault.

Can you provide some version information? Node, bunyan, os?

**Comment by Jiropole** [comment]
Bunyan 1.7.1, Node v4.2.6, OSX 10.11.3. The framework is autogenerated from Swagger.io and based on swagger-tools various validation and routing middleware. I think the only other module I've installed that uses compiled libs is bcrypt, and I haven't start working with that yet. May be a general issue with my installed C toolchain (xcode). I'll report back if it seems to be a general problem, but mostly I wanted to know if this sounded familiar.

**Comment by jsumners** [comment]
It is a problem. I can tell you it doesn't happen with version 1.3.5, but it definitely happens with version 1.7.1. And I have installed with `--no-optional`.

**Comment by rooftopsparrow** [comment]
Not sure if this helps but I've had no issue installing or executing on the exact setup.


```sh
$ sw_vers -productVersion
10.11.3
$ nvm use 4.2.6
Now using node v4.2.6 (npm v2.14.12)
$ npm install bunyan@1.7.1
> dtrace-provider@0.6.0 install ~/test/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

bunyan@1.7.1 node_modules/bunyan
├── safe-json-stringify@1.0.3
├── moment@2.11.2
├── mv@2.1.1 (ncp@2.0.0, mkdirp@0.5.1, rimraf@2.4.5)
└── dtrace-provider@0.6.0 (nan@2.2.0)

$ node -e 'require("bunyan").createLogger({ name: "myapp" }).info("hello")'
{"name":"myapp","hostname":"localhost","pid":55299,"level":30,"msg":"hello","time":"2016-03-04T19:26:33.199Z","v":0}
```

**Comment by jsumners** [comment]
@rooftopsparrow try running the app through the debugger.

**Comment by rooftopsparrow** [comment]
Still works over here
```
$ sw_vers -productVersion
10.11.3
$ nvm use 4.2.6
Now using node v4.2.6 (npm v2.14.12)
$ npm install bunyan@1.7.1
> dtrace-provider@0.6.0 install ~/test/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

bunyan@1.7.1 node_modules/bunyan
├── safe-json-stringify@1.0.3
├── moment@2.11.2
├── mv@2.1.1 (ncp@2.0.0, mkdirp@0.5.1, rimraf@2.4.5)
└── dtrace-provider@0.6.0 (nan@2.2.0)

$ cat << EOF > test.js
var bunyan = require("bunyan")
var logger = bunyan.createLogger({ name: "myapp" })
logger.info("hello")
EOF
$ node debug test.js
< Debugger listening on port 5858
debug> . ok
break in test.js:1
> 1 var bunyan = require("bunyan")
  2 var logger = bunyan.createLogger({ name: "myapp" })
  3 logger.info("hello")
debug> cont
< {"name":"myapp","hostname":"localhost","pid":61893,"level":30,"msg":"hello","time":"2016-03-04T20:25:13.237Z","v":0}
debug> quit
```

**Comment by jsumners** [comment]
Hmm, following your simple test it is working for me as well. But when I tried using 1.7.1 in [1], it would crash every time I tried to use the debugger. It happened as well with a new project (that isn't public). In both cases, downgrading bunyan "resolved" the issue.

[1] -- https://github.com/jsumners/node-activedirectory/tree/es2015

**Comment by Jiropole** [comment]
Same here, simple test did not crash. But even with createLogger as very first step in larger app, crashes immediately.

**Comment by leitsubomi** [comment]
Using 1.7.1, createLogger crashes while pause on debugger. In lib/bunyan.js line 580, the code is asserting stream and eagerly printing stream object
assert.ok(isWritable(s.stream),
                  '"stream" stream is not writable: ' + util.inspect(s.stream));
Even the assertion is true, util.inspect still access s.stream object. It crashes, while pause on debugger. 1.7.0 doesn't have this line.

**Comment by jsumners** [comment]
Has anyone figured out a solution to this? I'd like to switch to bunyan away from winston, but this bug is making it impossible.

**Comment by ttshaw** [comment]
it should be nodejs' bug, util.inspect, fixed in [https://github.com/nodejs/node/commit/24012a879d2fe17287a857ee20f696a78590db15](url)
(tried 4.4.2, it won't crash.)

**Comment by shaicantor** [comment]
any news with this?

**Comment by melloc** [comment]
It's possible that this was caused by chrisa/libusdt#12. Is anyone still having issues with this? If so, could you please try turning on core dumps by running `ulimit -c unlimited`, and then causing the segfault with a simple program that just calls `.createLogger()`?

On OS X, the core file should appear under `/cores`, and on other platforms it will usually be in the current directory. If you then have a core file, you can contact me and I can provide a place for you to upload it to.
